openapi: 3.0.0
info:
  title: CommonModels
  version: '1.0'
  description: 'Api containing common elements (ex. models, security schemes) for other apis'
  contact:
    name: K. Ziejło
    email: kziejlo@gmail.com
paths: {}
components:
  schemas:
    ErrorDTO:
      title: Error DTO
      type: object
      description: The DTO for backend errors.
      x-examples:
        Error Example:
          message: Error Message
          status: 503
          timestamp: '2019-08-24T14:15:22Z'
          code: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
      properties:
        message:
          type: string
          description: Translated error message
        status:
          type: integer
          description: The Error status
        timestamp:
          type: string
          format: date-time
          description: When did the error occur
        code:
          type: string
          format: uuid
          description: Unique code for each error occurence, make's it easier to search in logs
      required:
        - message
        - status
        - timestamp
        - code
    SimpleUserDTO:
      title: Simple User DTO
      type: object
      description: Class containing basic information on a user
      x-examples:
        Simple User Example:
          userType: simpleUser
          userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
          username: Username
      discriminator:
        propertyName: userType
        mapping:
          simpleUser: '#/components/schemas/SimpleUserDTO'
          completeUser: '#/components/schemas/CompleteUserDTO'
      properties:
        userType:
          type: string
          enum:
            - simpleUser
            - completeUser
        userId:
          $ref: '#/components/schemas/UserID'
        username:
          type: string
          description: 'ID of the Anime, the same used in Anilist.'
          minLength: 6
      required:
        - userType
        - userId
        - username
    CompleteUserDTO:
      title: Complete User DTO
      allOf:
        - $ref: ./CommonModels.yaml#/components/schemas/SimpleUserDTO
      properties:
        achievements:
          description: Set containing some achievements of the user
          type: array
          uniqueItems: true
          items:
            $ref: ./Achievement.yaml#/components/schemas/AchievementDTO
        animeInfos:
          description: Set containing some anime Information of the user
          type: array
          uniqueItems: true
          items:
            $ref: ./Anime.yaml#/components/schemas/LocalUserAnimeInformationDTO
        threads:
          description: Set containing some threads created by the user
          type: array
          uniqueItems: true
          items:
            $ref: ./Forum.yaml#/components/schemas/SimpleThreadDTO
        posts:
          description: Set containing some posts created by the user
          type: array
          uniqueItems: true
          items:
            $ref: ./Forum.yaml#/components/schemas/PostWithThreadInformationDTO
      required:
        - achievements
        - animeInfos
        - threads
        - posts
      description: Class containg complete information on a user.
      x-examples:
        Complete User Example:
          userType: completeUser
          userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
          username: Username
          achievements:
            - id: 5
              name: Achievement Name
              description: Achievement Description
              icon:
                - byte 1
                - byte 2
              points: 10
              nrOfUsersPosses: 3
          animeInfos:
            - id:
                userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                animeId: 195784
              status: No Status
              watchStartDate: '2019-08-24'
              watchEndDate: '2019-08-24'
              nrOfEpisodesSeen: 5
              isFavourite: true
              modification: '2019-08-24T14:15:22Z'
              grade: 2
              review:
                reviewType: simpleReview
                id: 1
                title: The Review Title
                text: The Review text
                nrOfUpvotes: 10
                nrOfDownvotes: 3
                nrOfHelpfull: 8
          threads:
            - threadComplexityType: simpleThread
              id: 7
              title: Thread Title
              nrOfPosts: 4
              status: OPEN
              creation: '2019-08-24T14:15:22Z'
              modification: '2019-08-24T14:15:22Z'
              creator:
                userType: simpleUser
                userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                username: Username
              category:
                id: 15
                name: Category Name
                description: Category Description
              tags:
                - id: 9
                  name: Tag Name
                  importance: LOW
                  color: 'rgb(789, 654, 321)'
              userStatus:
                id:
                  userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                  ThreadId: 8
                watching: true
                blocked: false
          posts:
            - id: 8
              title: Post Title
              text: Post Text
              creation: '2019-08-24'
              modification: '2019-08-26'
              creator:
                userType: simpleUser
                userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                username: Username
              nrOfPlus: 6
              nrOfMinus: 1
              userStatus:
                id:
                  userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                  postId: 8
                liked: true
                disliked: false
                reported: false
            - threadInformation:
                id: 7
                title: Thread Title
    UserID:
      type: string
      title: User ID
      format: uuid
      description: 'User ID, same as in Keycloak'
      x-examples:
        User Id Example: 497f6eca-6276-4993-bfeb-53cbbbba6f08
    DomainPageDTO:
      title: Page DTO
      type: object
      description: 'Class representing the Spring domain page DTO. This should be extended (and add the field: content: array[(Some Class)]) in order to get the desired content.'
      x-examples:
        Page Example:
          domainPageType: somePageType
          content:
            - name: Generic object
          nrOfElements: 1
          pageSize: 50
          pageNumber: 1
          totalPages: 1
          last: true
          empty: false
      discriminator:
        propertyName: domainPageType
        mapping:
          simpleThreadPage: '#/components/schemas/SimpleThreadPageDTO'
          simplePostPage: '#/components/schemas/SimplePostPageDTO'
          completePostPage: '#/components/schemas/CompletePostPageDTO'
      properties:
        domainPageType:
          type: string
          enum:
            - simpleThreadPage
            - simplePostPage
            - completePostPage
        nrOfElements:
          type: integer
          format: int32
          minimum: 0
          description: How many elements does the page contain
        pageSize:
          type: integer
          format: int32
          minimum: 0
          description: Size of the page
        pageNumber:
          type: integer
          format: int32
          minimum: 0
          description: Number of the page
        totalPages:
          type: integer
          format: int64
          minimum: 0
          description: How many total pates are there
        last:
          type: boolean
          description: Is this the last page
        empty:
          type: boolean
          description: Is the page empty
      required:
        - domainPageType
        - nrOfElements
        - pageSize
        - pageNumber
        - totalPages
        - last
        - empty
    SimpleThreadPageDTO:
      title: Simple Thread Page DTO
      type: object
      allOf:
        - $ref: '#/components/schemas/DomainPageDTO'
      properties:
        content:
          type: array
          items:
            $ref: ./Forum.yaml#/components/schemas/SimpleThreadDTO
      required:
        - content
      description: Domain Page extension for Simple Threads.
      x-examples:
        Simple Thread Page Example:
          domainPageType: simpleThreadPage
          content:
            - id: 8
              title: Thread Title
              nrOfPosts: 4
              status: OPEN
              creation: '2019-08-24T14:15:22Z'
              modification: '2019-08-24T14:15:22Z'
              creator:
                userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                username: Username
              category:
                id: 15
                name: Category Name
                description: Category Description
              tags:
                - id: 9
                  name: Tag Name
                  importance: LOW
                  color: 'rgb(789, 654, 321)'
              userStatus:
                id:
                  userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                  ThreadId: 8
                watching: true
                blocked: false
          nrOfElements: 1
          pageSize: 1
          pageNumber: 1
          totalPages: 1
          last: true
          empty: false
    SimplePostPageDTO:
      title: Simple Post Page DTO
      type: object
      allOf:
        - $ref: '#/components/schemas/DomainPageDTO'
      properties:
        content:
          type: array
          items:
            $ref: ./Forum.yaml#/components/schemas/SimplePostDTO
      required:
        - content
      description: Domain Page extension for Simple Posts.
      x-examples:
        Simple Post Page Example:
          domainPageType: simplePostPage
          content:
            - id: 8
              postComplexityType: simplePost
              title: Post Title
              text: Post Text
              creation: '2019-08-24'
              modification: '2019-08-26'
              creator:
                userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                username: Username
              nrOfLikes: 6
              nrOfDislikes: 1
              userStatus:
                id:
                  userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                  postId: 8
                liked: true
                disliked: false
                reported: false
          nrOfElements: 1
          pageSize: 50
          pageNumber: 1
          totalPages: 1
          last: true
          empty: false
    CompletePostPageDTO:
      title: Complete Post Page DTO
      type: object
      allOf:
        - $ref: '#/components/schemas/DomainPageDTO'
      properties:
        content:
          type: array
          items:
            $ref: ./Forum.yaml#/components/schemas/CompletePostDTO
      required:
        - content
      description: Domain Page extension for Complete Posts.
      x-examples:
        Complete Post Page Example:
          responses:
            content:
              - responses: {}
                id: 8
                title: Post Title
                text: Post Text
                creation: '2019-08-24'
                modification: '2019-08-26'
                creator:
                  userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                  username: Username
                nrOfLikes: 6
                nrOfDislikes: 1
                status: OPEN
                userStatus:
                  id:
                    userType: simpleUser
                    userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                    postId: 8
                  liked: true
                  disliked: false
                  reported: false
            domainPageType: completePostPage
            nrOfElements: 1
            pageSize: 1
            pageNumber: 0
            totalPages: 1
            last: true
            empty: false
          id: 8
          title: Post Title
          text: Post Text
          creation: '2019-08-24'
          modification: '2019-08-26'
          creator:
            userType: simpleUser
            userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
            username: Username
          nrOfLikes: 6
          nrOfDislikes: 1
          status: NO_PROBLEM
          userStatus:
            id:
              userType: simpleUser
              userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
              postId: 8
            liked: true
            disliked: false
            reported: false
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Uses a token created by Keykloak to authenticate the User. The token needs to be reloaded every 15 minutes
